runtime: nodejs20 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "matheus"

handlers:
  - url: /robots.txt
    static_files: dist/robots.txt
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      # Content-Security-Policy: default-src 'self'
      Referrer-Policy: strict-origin-when-cross-origin
      Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
    upload: dist/robots.txt

  - url: /sitemap.xml
    static_files: dist/sitemap.xml
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      # Content-Security-Policy: default-src 'self'
      Referrer-Policy: strict-origin-when-cross-origin
      Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
    upload: dist/sitemap.xml

  - url: /assets
    static_dir: dist/assets
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      # Content-Security-Policy: default-src 'self'
      Referrer-Policy: strict-origin-when-cross-origin
      Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
    expiration: 7d

  - url: /img
    static_dir: dist/img
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      # Content-Security-Policy: default-src 'self'
      Referrer-Policy: strict-origin-when-cross-origin
      Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
    expiration: 7d

  - url: /i18n
    static_dir: dist/i18n
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      # Content-Security-Policy: default-src 'self'
      Referrer-Policy: strict-origin-when-cross-origin
      Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()

  - url: /(.*\.(json|ico|js))$
    static_files: dist/\1
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      # Content-Security-Policy: default-src 'self'
      Referrer-Policy: strict-origin-when-cross-origin
      Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
    upload: dist/.*\.(json|ico|js)$
    expiration: 7d

  - url: /
    secure: always
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      # Content-Security-Policy: default-src 'self'
      Referrer-Policy: strict-origin-when-cross-origin
      Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
    redirect_http_response_code: 301
    static_files: dist/index.html
    upload: dist/index.html

  - url: /.*
    secure: always
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      # Content-Security-Policy: default-src 'self'
      Referrer-Policy: strict-origin-when-cross-origin
      Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
    static_files: dist/index.html
    upload: dist/index.html

######### optional gae flex config (run from dist folder) ########
# runtime: nodejs
# env: flex
# 
# config optimized for demo for cost savings (not production)
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
# memory_gb: 0.5
# disk_size_gb: 10